### ISSUE TITLE
Release with updated dependency

### ISSUE THREAD

**Issue by Alakazam03** [SergioBenitez/cookie-rs#128]
Thanks for the great framework. 
I am trying to use merkle tree from spinresearch but i am getting a dependency error.

error: failed to select a version for `ring`.
    ... required by package `merkle v1.11.0`
    ... which is depended on by `filtering-service v0.1.0 (/Users/alakazam/Documents/projects/RUST/filtering-service)`
versions that meet the requirements `^0.16.1` are: 0.16.9, 0.16.7, 0.16.6, 0.16.5, 0.16.4, 0.16.3, 0.16.2, 0.16.1

the package `ring` links to the native library `ring-asm`, but it conflicts with a previous package which links to `ring-asm` as well:
package `ring v0.13.5`
    ... which is depended on by `cookie v0.11.0`
    ... which is depended on by `rocket_http v0.4.2`
    ... which is depended on by `rocket v0.4.2`
    ... which is depended on by `filtering-service v0.1.0 (/Users/alakazam/Documents/projects/RUST/filtering-service)`

failed to select a version for `ring` which could resolve this conflict.

I tried using replace also but didnt work for me. Please can we do something @SergioBenitez @jebrosen

**Comment by Alakazam03** [comment]
Hi, sorry for bothering again. I have my whole graduation project built on your framework. Please if you can help. @SergioBenitez @jebrosen

**Comment by jebrosen** [comment]
I agree that the ring version is a frustrating situation. The two easiest solutions I see for you are:

* Use the previous version of `merkle`, which is nearly identical to the version you are using. Because it is only different by a minor version, you will have to be a bit more explicit than usual about the version in `Cargo.toml`: `merkle = ">=1.10, <1.11"`
* disable `private-cookies` in Rocket, if you are not using it. This would mean specifying `default-features = false` for `rocket` in `Cargo.toml`

**Comment by Alakazam03** [comment]
I am not using private-cookies and I did as mentioned above.
1. changing Cargo.toml: merkle = ">=1.10, <1.11" didnt work. I have to use ring as a direct dependency for hashing. It gives rise to a conflict at that time.
2. disabling private-cookies worked smoothly for me.

Thanks for the help.

**Comment by jebrosen** [comment]
> changing Cargo.toml: merkle = ">=1.10, <1.11" didnt work. I have to use ring as a direct dependency for hashing. It gives rise to a conflict at that time.

Ah, the error message doesn't indicate that (I believe it only prints the first two conflicts it sees). In that case you would have also had to downgrade your own dependency on ring to `0.13`.

But since you are not using private cookies, that is a better solution as you can use the latest version of ring.

**Comment by Alakazam03** [comment]
I tried that degrading the dependecy of ring = "0.13". But some of the functions I have to use were not present in 0.13. 
I went with the second one but I have to find a concrete solution before I start using private-cookies.

Thanks for the help. Appreciate that.
