### ISSUE TITLE
rustdoc fail on stable

### ISSUE THREAD

**Issue by algesten** [SergioBenitez/cookie-rs#151]
I tried updating to 0.14 in one of my project. This stopped rustdoc from working. It's the `feature(doc_cfg)` that isn't allowed on stable. Is this intentional?

```
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /Users/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/cookie-0.14.1/src/lib.rs:77:37
   |
77 | #![cfg_attr(all(doc, not(doctest)), feature(doc_cfg))]
   |                                     ^^^^^^^^^^^^^^^^
```

**Comment by SergioBenitez** [comment]
Yes, this is intentional. The crate compiles and tests on stable, but the docs now require nightly to build. Is this an issue? Are you unable to use nightly to build documentation? It would be fairly straightforward to detect if nightly is being used and only then try to use the nightly feature when building docs, if necessary.

**Comment by algesten** [comment]
Not a huge problem. I'm just not used to switch to nightly for anything, so let's just call my woes a "mild inconvenience" :)

**Comment by SergioBenitez** [comment]
Recall that you can use `+nightly` for one-off commands: `cargo +nightly doc`, for instance. In any either case, I'll close out the issue. :)
