### ISSUE TITLE
v0.15.1 missing on crates.io

### ISSUE THREAD

**Issue by asaaki** [SergioBenitez/cookie-rs#175]
Hi @SergioBenitez.

Thank you for this project and for taking quick action around the dependency updates for the crypto parts.
I see you already updated the GH repo, but I cannot see a published version on crates.io yet.

Would you be so kind to check/publish? That way I can also work my way downstream up to my projects.

**Comment by SergioBenitez** [comment]
My final release testing found that `0.15.1` would have been a breaking change due to a bump in MSRV: https://github.com/SergioBenitez/cookie-rs/pull/174#issuecomment-831871732. As such, I am holding off until this is resolved.

> Would you be so kind to check/publish? That way I can also work my way downstream up to my projects.

You shouldn't need to update anything unless you want to force `0.15.1` on users. Otherwise, the next `cargo update` will bring in the new deps.

**Comment by asaaki** [comment]
Sadly doesn't work for some dependencies of my project.
For example http_types has still 0.14.0 encoded, so it doesn't even bring 0.15 in at all.

**Comment by asaaki** [comment]
@ MSRV: that is very unfortunate. I hope that gets resolved soon. 🤗

**Comment by SergioBenitez** [comment]
I'm closing this as there's nothing really to track. As soon as the issues in https://github.com/SergioBenitez/cookie-rs/pull/174#issuecomment-831871732 are resolved, we'll get a 0.15.1 with the changes.
