### ISSUE TITLE
Set Removal Cookies SameSite to Lax

### ISSUE THREAD

**Issue by genusistimelord** [SergioBenitez/cookie-rs#215]
The issue is Removal cookies don't get a Same Site setting which browsers are starting to Require Or presetting them as Lax. Inserting the Same site as Lax will prevent the Browser from displaying Warning messages and maybe Error messages later based on the action the browser take.

**Comment by SergioBenitez** [comment]
The treatment of cookies without a `SameSite` attribute is to place them inside of a ["default" enforcement domain](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis#section-5.5.7) which browsers may [treat differently to lax](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis#name-lax-allowing-unsafe-enforce), though they should be equivalent after some arbitrarily chosen time. Irrespective of this, the latest draft RFC does not raise any concerns about removing cookies with SaneSite attributes, and I wouldn't expect browsers to trigger a warning on cookies not containing a SameSite attribute if they have an expiration date in the past. There's no point in doing so: the cookie will never be sent anywhere, so it can't possibly pose a security threat.

Do you have any evidence to indicate that browsers do or will do otherwise?

**Comment by genusistimelord** [comment]
I would agree with you here But here is one from firefox.
![image](https://github.com/SergioBenitez/cookie-rs/assets/1034709/815bdeef-9f55-4cca-8106-2dffc3342fb7)

![image2](https://github.com/SergioBenitez/cookie-rs/assets/1034709/3b752f3b-73a5-4fe4-9b7f-3e2f94047609)

**Comment by SergioBenitez** [comment]
That feels like an issue for web browsers, not one that we should paper over here. The goal of this library is to be foundational and correct, not opinionated. For this reason, we don't arbitrarily set SameSite attributes, or any other attributes, for any cookies in this library, and I don't think we should set them for removal cookies either. Should our position on that change, we can revisit this issue then. Until then, I'm closing this out.

Note: If you're using a web framework that uses this library, I would advocate that you raise an issue there. Web frameworks can be more opinionated. Rocket sets SameSite attributes automatically, for example.
